### PR TITLE
Added margin to left of logo

### PR DESCRIPTION
**Pull request by apfunk**
I added some some margin to the left of the map chat logo.

### CODE REVIEW

**Comment by idoco** [comment]
Hi thanks for the contribution.
I've tested the change, and on mobile when the logo is centered this looks a little off :)

image

I think it wil be better to look into the right way to do it using the materializecss.com considering the current window size.

**Comment by apfunk** [comment]
The navbar now uses the fluid grid layout. I also updated the meta tag to reflect materialize's recommended meta tag.

**Comment by idoco** [comment]
Looks good but I couldn't test that, I think you need to sync with the main branch before I can merge it :)
There were several minor changes in the last days.

**Comment by idoco** [comment]
Hi, I think I will just move the Logo to the center like in mobile mode.

**Comment by apfunk** [comment]
That works.

**Pull request closed without merging**
