### PR TITLE
Gives a 2 second timeout for all infowindows. Helps cleanup the map-chat

### PR DESCRIPTION
**Pull request by Rockdtben**
This is pretty nice. It makes the chat boxes close automatically after 2 seconds. Since the volume of messages are so high now. I figured this would be useful.

### CODE REVIEW

**Comment by idoco** [comment]
Thanks for the contribution!
Right now when there aren't so many people in MapChat I think it is best to still leave the infowindows opened. It creates a more active atmosphere and let you wonder to others tabs and still catch some of the conversation when you get back to it. 

I will keep this open for the future, in case the conditions change.
Thanks.

P.S I'll also start fixing the project so it will be simple to run and test locally. Currently some of the properties in the main branch are not set in a good way to enable that.

**Comment by idoco** [comment]
This was implemented in [this commit](https://github.com/idoco/map-chat/commit/31d3ea18b94a520d894e8b2a6326ae00fc061f86) with a hard-coded 10 seconds time out. we can improve this in the future. 
Thanks!

**Comment by Rockdtben** [comment]
:+1: No problem.

**Comment by Rockdtben** [comment]
Hmm. If you want people to work with you then you should suggest how they could fix their PRs and then you should merge their PRs when they fix them. In this case I don't get any credit for working on this project.

**Comment by idoco** [comment]
Sorry about that, you are right, I will try to improve :worried: 
Sometimes I just feel that it would be easier to implement something than to explain my intentions, but I know this is a bad way to encourage collaboration.

Point taken.

**Pull request closed without merging**
